## Polynomial regression

In [1]:
import pandas as pd
import numpy as np

In [2]:
# veriyi oku
df = pd.read_csv('Power_Plant.csv', delimiter=",")
df.head()

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [3]:
# girdileri ve çıktı sutunlarını x ve y değişkenine ata
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [4]:
# Veri setini Eğitim seti ve Test seti olarak ayırma
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [5]:
# Standard Scaling

from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
x_train_scaled = standard_scaler.fit_transform(x_train)
x_test_scaled = standard_scaler.transform(x_test)

In [6]:
# İlgili kütüphaneyi import et.
from sklearn.preprocessing import PolynomialFeatures
poly_reg_feature_builder = PolynomialFeatures(degree = 5)
x_train_poly = poly_reg_feature_builder.fit_transform(x_train_scaled)
x_train_scaled

array([[ 1.46330823,  1.49020257, -2.17249645,  0.05546147],
       [ 0.46431604,  0.88163605,  0.13758176, -1.81811087],
       [ 0.14426358, -0.95741271, -0.51497318, -0.67892418],
       ...,
       [ 0.4669943 , -0.23891159, -0.64986826,  0.5641979 ],
       [ 0.32906375, -0.67707949,  0.17636409,  0.30025669],
       [-0.81991118, -0.6323204 ,  0.82554666,  1.0271207 ]])

In [7]:
# Polinom Regresyon modelini eğitin

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train_poly, y_train)

LinearRegression()

In [8]:
# Test datasına ait polinom özelliklerini hazırla ve Test verilerini kullanarak çıktıyı tahmin et

x_test_poly = poly_reg_feature_builder.fit_transform(x_test_scaled)

y_pred = regressor.predict(x_test_poly)

In [9]:
y_pred_df = pd.DataFrame(data=y_pred,columns=["Tahmini_Sonuc"])

In [10]:
y_test_df = pd.DataFrame(data=y_test,columns=["Gerçek_Sonuç"])

karsılastırma_df = pd.concat([y_test_df,y_pred_df],axis=1)
karsılastırma_df

      Gerçek_Sonuç  Tahmini_Sonuc
0           440.17     435.828565
1           450.86     448.351026
2           441.76     438.847538
3           464.95     462.151115
4           467.62     468.057900
...            ...            ...
1889        430.92     435.665320
1890        466.83     466.330102
1891        446.75     449.941724
1892        449.99     453.405708
1893        440.46     438.144396

[1894 rows x 2 columns]

In [11]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9415959051622281

In [12]:
unseen_dataset_df = pd.read_csv('Power_Plant_Unseen.csv', delimiter=";")
unseen_dataset_df.head(10)

      AT      V       AP     RH
0  12.45  40.56  1017.84  66.52
1  16.70  40.56  1019.04  50.90
2  19.88  44.60  1015.52  37.85
3  19.64  46.33  1013.33  98.99
4  20.01  59.87  1019.00  84.12
5  16.27  58.20  1018.47  80.03
6  10.80  41.39  1019.74  74.08
7   9.64  39.35  1015.10  91.76
8  11.53  41.14  1025.63  88.54
9  21.83  63.07  1011.57  87.02

In [13]:
# unseen_dataset
unseen_dataset = unseen_dataset_df.iloc[:, :].values
unseen_dataset

array([[  12.45,   40.56, 1017.84,   66.52],
       [  16.7 ,   40.56, 1019.04,   50.9 ],
       [  19.88,   44.6 , 1015.52,   37.85],
       [  19.64,   46.33, 1013.33,   98.99],
       [  20.01,   59.87, 1019.  ,   84.12],
       [  16.27,   58.2 , 1018.47,   80.03],
       [  10.8 ,   41.39, 1019.74,   74.08],
       [   9.64,   39.35, 1015.1 ,   91.76],
       [  11.53,   41.14, 1025.63,   88.54],
       [  21.83,   63.07, 1011.57,   87.02],
       [   9.51,   40.46, 1018.84,   70.12],
       [  28.84,   75.6 , 1018.41,   53.96],
       [  25.82,   72.39, 1003.4 ,   86.33],
       [  28.47,   69.23, 1013.18,   40.73],
       [  19.87,   49.69, 1012.23,   68.57],
       [  14.38,   44.84, 1024.59,   81.68],
       [  27.37,   65.06, 1013.09,   50.92],
       [  28.05,   62.6 , 1017.01,   46.46],
       [   8.66,   36.25, 1028.22,   86.96],
       [  16.61,   45.87, 1009.34,   97.93],
       [  11.28,   42.44, 1014.62,   99.78],
       [  21.1 ,   62.66, 1011.19,   83.49],
       [  16.47,   44.89, 1010.04,   82.01],
       [  30.39,   71.8 , 1010.87,   64.11],
       [   8.29,   36.08, 1020.38,   81.53],
       [  28.9 ,   68.12, 1011.87,   46.56],
       [  18.42,   58.95, 1016.95,   86.77],
       [  18.13,   66.86, 1012.9 ,   78.84],
       [  26.27,   58.33, 1013.81,   60.43],
       [  26.05,   73.88, 1005.67,   82.08],
       [  18.2 ,   52.72, 1025.87,   54.26],
       [  31.04,   66.54, 1003.83,   53.05],
       [  21.67,   62.39, 1007.98,   92.96],
       [  24.48,   50.23, 1017.03,   66.89],
       [  24.41,   73.67, 1007.39,   86.92],
       [  12.77,   36.71, 1013.29,   86.4 ],
       [  13.51,   40.89, 1011.03,   84.83],
       [  32.13,   74.34, 1003.34,   56.39],
       [  19.68,   62.96, 1020.41,   82.26],
       [  26.87,   74.99, 1002.48,   71.91],
       [  25.63,   56.85, 1012.68,   49.7 ],
       [  19.39,   60.1 , 1010.28,   83.31],
       [  13.84,   42.18, 1015.74,   79.76],
       [  24.6 ,   57.32, 1012.48,   45.14],
       [  34.14,   74.34, 1000.19,   43.56],
       [  29.61,   67.07, 1005.91,   39.28],
       [  31.94,   74.99, 1002.05,   34.12],
       [  26.98,   43.77, 1010.95,   40.8 ],
       [  15.92,   37.64, 1014.93,   83.73],
       [  14.49,   41.92, 1030.3 ,   56.62],
       [  26.71,   76.86, 1002.86,   74.5 ],
       [  26.73,   49.02, 1007.75,   67.73],
       [  28.53,   49.3 , 1003.83,   59.69],
       [  26.85,   75.6 , 1017.43,   74.55],
       [  10.25,   37.14, 1013.14,   70.73],
       [  10.88,   44.63, 1020.52,   86.81],
       [  26.75,   64.79, 1017.79,   54.31],
       [  13.45,   43.14, 1015.5 ,   74.33],
       [  23.96,   65.34, 1015.52,   56.82],
       [  14.32,   45.08, 1023.24,   84.53],
       [  13.16,   40.71, 1021.99,   77.91],
       [  23.4 ,   65.06, 1014.32,   67.38],
       [  26.5 ,   66.75, 1018.48,   61.62],
       [   7.39,   39.85, 1011.63,   83.61],
       [  25.97,   70.32, 1007.48,   57.01],
       [  25.99,   74.67, 1016.59,   83.39],
       [  25.87,   44.57, 1007.43,   55.92],
       [  28.66,   77.95, 1009.56,   69.07],
       [   7.84,   41.39, 1018.21,   91.92],
       [  31.91,   69.89, 1014.59,   54.51],
       [  31.94,   69.98, 1013.32,   56.17],
       [  30.03,   70.02, 1010.07,   64.2 ],
       [  22.43,   63.94, 1012.76,   93.24],
       [  22.86,   58.96, 1014.03,   54.96],
       [  14.05,   40.35, 1011.52,   66.21],
       [  12.04,   41.58, 1018.02,   88.91],
       [  19.31,   44.71, 1016.13,   30.59],
       [  16.76,   43.77, 1012.25,   77.95],
       [  31.5 ,   70.32, 1011.44,   64.09],
       [  14.43,   35.85, 1021.99,   78.25],
       [   9.39,   41.79, 1021.6 ,   50.09],
       [  25.15,   62.91, 1012.23,   48.22],
       [   9.66,   41.82, 1033.19,   73.19],
       [  18.31,   42.23, 1012.88,   79.32],
       [  28.21,   70.02, 1010.58,   51.34],
       [  17.48,   58.95, 1016.49,   90.35],
       [  19.92,   38.52, 1018.15,   60.68],
       [  23.1 ,   70.79, 1006.53,   90.81],
       [  22.61,   54.42, 1014.74,   75.87],
       [  25.6 ,   63.76, 1010.18,   67.43],
       [  25.84,   67.83, 1009.26,   59.55],
       [  22.99,   60.95, 1015.14,   69.86],
       [  22.61,   45.38, 1013.92,   62.91],
       [  17.54,   44.58, 1016.56,   79.  ],
       [  26.18,   52.36, 1013.46,   56.65],
       [  20.97,   47.43, 1007.64,   71.18],
       [  14.1 ,   41.16, 1021.26,   73.87],
       [  17.83,   66.86, 1011.65,   77.31],
       [   8.46,   40.8 , 1023.57,   81.27],
       [  30.92,   78.05, 1011.  ,   59.62]])

In [14]:
# Standard Scaling

unseen_dataset_scaled = standard_scaler.transform(unseen_dataset)

In [15]:
# İlgili kütüphaneyi import et.
from sklearn.preprocessing import PolynomialFeatures
poly_reg_feature_builder = PolynomialFeatures(degree = 5)
unseen_dataset_scaled_poly = poly_reg_feature_builder.fit_transform(unseen_dataset_scaled)
unseen_dataset_scaled_poly

array([[ 1.00000000e+00, -9.57841736e-01, -1.07362928e+00, ...,
        -6.11487018e-02,  3.69794016e-02, -2.23631264e-02],
       [ 1.00000000e+00, -3.88710799e-01, -1.07362928e+00, ...,
        -3.44734360e+00,  5.42642134e+00, -8.54166336e+00],
       [ 1.00000000e+00,  3.71330554e-02, -7.56389445e-01, ...,
        -2.08967190e+00,  1.32795092e+01, -8.43890201e+01],
       ...,
       [ 1.00000000e+00, -2.37388926e-01,  9.91570647e-01, ...,
         1.44267653e-03, -1.44104583e-03,  1.43941697e-03],
       [ 1.00000000e+00, -1.49215525e+00, -1.05478335e+00, ...,
         4.78959430e-01,  1.48950017e-01,  4.63214757e-02],
       [ 1.00000000e+00,  1.51553436e+00,  1.87026218e+00, ...,
        -1.19773796e-01, -2.96047231e-01, -7.31745722e-01]])

In [16]:
y_pred_unseen = regressor.predict(unseen_dataset_scaled_poly)
y_pred_unseen

array([472.04597911, 466.35175529, 461.6745136 , 456.95942977,
       449.46614418, 459.61584942, 476.32986537, 477.50017382,
       470.75106725, 444.61459263, 479.11005032, 439.51063342,
       433.36692122, 437.26003936, 453.67101896, 465.287073  ,
       440.34790373, 441.55709939, 476.86521056, 457.33229386,
       469.76590195, 446.26936984, 460.35795692, 432.72855523,
       481.61774852, 437.12306842, 452.98386571, 451.32002767,
       444.44330791, 433.90707251, 459.5333307 , 430.68569563,
       443.06173216, 449.5773881 , 435.89133858, 472.10386939,
       469.05902847, 431.24335005, 450.18226017, 434.73758274,
       445.63112652, 449.48246736, 468.25749457, 447.38326599,
       431.07920024, 434.26758807, 431.00049669, 444.80926367,
       465.43518076, 469.6844843 , 435.36305979, 440.61955838,
       436.93208703, 436.33855244, 476.96679079, 474.36056118,
       441.41597432, 469.18500306, 444.87845623, 465.0931648 ,
       469.30488123, 444.51671003, 439.80036906, 483.86287998,
       439.40780226, 433.15846387, 444.1652998 , 433.22338886,
       481.35006671, 432.02740225, 432.44053013, 433.78170943,
       442.37023327, 448.97986305, 468.17370947, 470.84641738,
       463.47500121, 461.25488797, 432.24465537, 463.81193919,
       481.89959612, 444.54815856, 477.31045565, 459.7471792 ,
       436.95215765, 454.02966598, 461.68761543, 438.09535518,
       449.2203175 , 440.48681909, 439.3787687 , 446.89468916,
       453.83742608, 460.1661434 , 447.42441875, 450.10504861,
       467.74315346, 451.30275024, 482.01136876, 432.99191765])

In [17]:
y_pred_unseen_df = pd.DataFrame(y_pred_unseen, columns=["Tahmini_Output"])
y_pred_unseen_df.head(10)

   Tahmini_Output
0      472.045979
1      466.351755
2      461.674514
3      456.959430
4      449.466144
5      459.615849
6      476.329865
7      477.500174
8      470.751067
9      444.614593

In [18]:
all_df = pd.concat([unseen_dataset_df,y_pred_unseen_df],axis=1)
all_df

       AT      V       AP     RH  Tahmini_Output
0   12.45  40.56  1017.84  66.52      472.045979
1   16.70  40.56  1019.04  50.90      466.351755
2   19.88  44.60  1015.52  37.85      461.674514
3   19.64  46.33  1013.33  98.99      456.959430
4   20.01  59.87  1019.00  84.12      449.466144
..    ...    ...      ...    ...             ...
95  20.97  47.43  1007.64  71.18      450.105049
96  14.10  41.16  1021.26  73.87      467.743153
97  17.83  66.86  1011.65  77.31      451.302750
98   8.46  40.80  1023.57  81.27      482.011369
99  30.92  78.05  1011.00  59.62      432.991918

[100 rows x 5 columns]